---
# tasks file for ansible-kafka

- name: Launch kafka
  docker:
    image: xpatterns/kafka:{{ kafka_version }}
    name: kafka
    command: /usr/bin/run.sh {{ docker_command }}
    net: host
    volumes:
      - "{{ data_dir }}/kafka:/tmp/kafka-logs"
    restart_policy: always
    state: started
    env:
      ZOOKEEPERHOST: "{{ zookeeper_host }}"
