---
# tasks file for ansible-kafka

- name: Launch kafka
  docker:
    image: xpatterns/kafka:{{ kafka_version }}
    name: kafka
    command: /usr/bin/run.sh
    net: host
#    hostname: kafka
#    ports: 
#      - "9092:9092"
    volumes:
      - "{{ data_dir }}/kafka:/tmp/kafka-logs"
    restart_policy: always
    state: started
    env:
      ZOOKEEPERHOST: "{{ zookeeper_host }}"
